### PR TITLE
fix: fix rubocop warnings and specs

### PR DESCRIPTION
**Pull request by oleksii-leonov**
- fixed current rubocop warnings;
- frozen `rubocop` and `rubocop-performance` versions to avoid CI break when rubocop rules are changed in new versions;
- turned on GitHub actions for PRs;
- fixed specs (FFI::Function return_type/result_type for FFI 1.16+);
- made Continuous Integration workflow specs runnable (however, some specs are failing with GDAL 3).

### CODE REVIEW

**Comment by oleksii-leonov** [comment]
@turboladen @tindron 

What is the policy for GDAL 2 support?
Right now, all specs are passing for GDAL 2, but some specs are failing for GDAL 3.

Should I fix the specs to work correctly with GDAL 3 and ignore GDAL 2 as outdated (as Ubuntu 20.04+ shipped with GDAL 3)?
Or should both GDAL 2 and GDAL 3 be supported in specs?

**Comment by turboladen** [comment]
> Or should both GDAL 2 and GDAL 3 be supported in specs?

Thanks for asking--and again, thanks for your contributions of late. My apologies for the lag in getting back to you on many of your PRs; I plan on getting back to you next week on them.

Unfortunately, we'll need to support GDAL 2 for a bit. We haven't yet spent any time yet working on official GDAL 3 support (which goes without saying is long overdue), but it sounds like this is a good impetus for us to start putting that plan together. Certainly the long term plan is to ditch GDAL 2 support, but right now some of our legacy apps depend on GDAL 2, hence the need for that right now.

**Comment by turboladen** [comment]
> There are 10 specs failing for GDAL 3. I will make those specs work properly for GDAL 2 and GDAL 3.

Sweet, thank you!

> However, I believe it would be good to merge this PR in its current state. This PR fixes rubocop warnings and specs for GDAL 2 (related to FFI 1.16 breaking changes).

Agreed.

**Comment by oleksii-leonov** [comment]
@turboladen

GDAL 3 specs fixed: https://github.com/telus-agcg/ffi-gdal/pull/81

**Pull request merged**
